I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 275, in script
    python:
  File "renpy/common/00start.rpy", line 275, in script
    python:
  File "renpy/common/00start.rpy", line 279, in <module>
    renpy.call_in_new_context("_main_menu")
  File "game/achievements/achievement_screen.rpy", line 116, in passive_function
    Achievement.add(achievement_name['wow'])
KeyError: 'wow'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\marce\Documents\Renpy\renpy-8.1.1-sdk\renpy\bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "C:\Users\marce\Documents\Renpy\renpy-8.1.1-sdk\renpy\main.py", line 670, in main
    run(restart)
  File "C:\Users\marce\Documents\Renpy\renpy-8.1.1-sdk\renpy\main.py", line 144, in run
    renpy.execution.run_context(True)
  File "C:\Users\marce\Documents\Renpy\renpy-8.1.1-sdk\renpy\execution.py", line 955, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 275, in script
    python:
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 444, in raise_
  File "renpy/common/00start.rpy", line 275, in script
    python:
  File "C:\Users\marce\Documents\Renpy\renpy-8.1.1-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\marce\Documents\Renpy\renpy-8.1.1-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 279, in <module>
    renpy.call_in_new_context("_main_menu")
  File "C:\Users\marce\Documents\Renpy\renpy-8.1.1-sdk\renpy\game.py", line 349, in call_in_new_context
    return renpy.execution.run_context(False)
  File "C:\Users\marce\Documents\Renpy\renpy-8.1.1-sdk\renpy\execution.py", line 955, in run_context
    context.run()
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in script
    python hide:
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 444, in raise_
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in script
    python hide:
  File "C:\Users\marce\Documents\Renpy\renpy-8.1.1-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\marce\Documents\Renpy\renpy-8.1.1-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in <module>
    python hide:
  File "renpy/common/_layout/screen_main_menu.rpym", line 35, in _execute_python_hide
    ui.interact()
  File "C:\Users\marce\Documents\Renpy\renpy-8.1.1-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\marce\Documents\Renpy\renpy-8.1.1-sdk\renpy\display\core.py", line 3582, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\marce\Documents\Renpy\renpy-8.1.1-sdk\renpy\display\core.py", line 4377, in interact_core
    i()
  File "game/achievements/achievement_screen.rpy", line 116, in passive_function
    Achievement.add(achievement_name['wow'])
KeyError: 'wow'

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
Le Cirque de la Passion 1.0
Sun Jan 28 12:34:34 2024
